apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-md-docs-ingress
  namespace: docs
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: docs-tailscale-ip-only@kubernetescrd,docs-local-docs-redirect@kubernetescrd,docs-local-docs-strip@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: oci-arm-4.gannet-justitia.ts.net
    http:
      paths:
      - path: /local-docs
        pathType: Prefix
        backend:
          service:
            name: local-md-docs
            port:
              number: 80
  tls:
  - hosts:
    - oci-arm-4.gannet-justitia.ts.net
    secretName: tailscale-tls-oci-arm-4
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: local-md-docs-ip-route
  namespace: docs
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: (Host(`oci-arm-4.gannet-justitia.ts.net`) || Host(`100.115.101.108`)) && PathPrefix(`/local-docs`)
      kind: Rule
      middlewares:
        - name: tailscale-ip-only
        - name: local-docs-redirect
        - name: local-docs-strip
      services:
        - name: local-md-docs
          port: 80
    - match: (Host(`oci-arm-4.gannet-justitia.ts.net`) || Host(`100.115.101.108`)) && Path(`/`)
      kind: Rule
      middlewares:
        - name: tailscale-ip-only
        - name: root-to-localdocs
      services:
        - name: local-md-docs
          port: 80
  tls:
    secretName: tailscale-tls-oci-arm-4
